<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MetaBrain.Connections</AssemblyName>
    <RootNamespace>MetaBrain.Connections</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MetaBrain.Core\MetaBrain.Core.csproj" />
    <ProjectReference Include="..\MetaBrain.Application\MetaBrain.Application.csproj" />
  </ItemGroup>
</Project>
